Repository MewsSystems/gitbook-channel-manager-api, pull requests merged in 2024-10, with the labels that each got.

#186 Updated guidelines for channels
  changelog/README.md
  guidelines/README.md
Labels: documentation-only

#189 CON-4123: Availability block via channel manager api - documentation
  changelog/README.md
  mews-operations/availabilityBlock.md
  mews-operations/operations.md
Labels: con.distribution

#188 Con 4085 new field in availability block
  changelog/README.md
  channel-manager-operations/availabilityBlock.md
Labels: con.distribution

#192 Auto labeling added
  .github/workflows/add-label.yaml
Labels: documentation-only, con.distribution

#191 Con 4154: Release strategy for block synchronization and block processing - update document
  changelog/README.md
  channel-manager-operations/availabilityBlock.md
  deprecations/README.md
  mews-operations/availabilityBlock.md
Labels: con.distribution

#193 Added PickupType in Availability block from them to us
  changelog/README.md
  mews-operations/availabilityBlock.md
Labels: con.distribution

#194 Quick fix to Changelog
  changelog/README.md
Labels: documentation-only, con.distribution

#195 Deprecated loyaltyCode in favor of loyaltyInfo
  changelog/README.md
  deprecations/README.md
  mews-operations/reservations.md
Labels: documentation-only, con.distribution
